info:
  component: WB3 Zuul Edge Server
server:
  port: 3003
management:
  security:
    enabled: false
zuul:
  ignoredService: '*'
  routes:
    api:
      path: /api/**
    sandbox:
      path: /sandbox-api/**
  endpoints:
    restart:
      enbale: true
    shutdown:
      enable: true
    health:
      sensitive: false
eureka:
    instance:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
      serviceUrl:
        defaultZone: http://msdiscovery:3002/eureka/
      healthcheck:
        enabled: true
      registerWithEureka: true
      fetchRegistry: true
      registry-fetch-interval-seconds: 5
logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO